---
  # This Task Configures 1 or more DNS Servers in UCSM
  # Configure DNS Servers
  - name: Configure DNS server
    ucs_dns_server:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      dns_server: "{{ item.ip_address }}"
      description: DNS Server IP address
      state: present
      delegate_to: localhost
    with_list: "{{ dns_servers }}"
    when: dns_servers is defined
