---
# Configuration of vNIC Templates except iSCSI vNIC Templates
# These templates are all setup as updating Templates with MTU set to 9000
#
- name: Configure vNIC Templates
  cisco.ucs.ucs_vnic_template:
    hostname: "{{ inventory_hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    name: "{{ item.name }}"
    fabric: "{{ item.fabric }}"
    org_dn: org-root/org-{{ organization }}
    mac_pool: "{{ item.mac_pool }}"
    mtu: '9000'
    network_control_policy: "{{ NCP_name }}"
    peer_redundancy_template: "{{ item.redundant_peer }}"
    redundancy_type: "{{ item.redundancy_type }}"
    template_type: 'updating-template'
    vlans_list: "{{ item.vlans }}"
  with_list: "{{ vnic_template_list}}"
