
---
# Configure MAC Pool A and B on UCS
#
- name: Configure MAC address pool for Fabric-A,B
  ucs_mac_pool:
    hostname: "{{ inventory_hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    name: "{{ item.name }}"
    first_addr: "{{ item.first_mac }}"
    last_addr: "{{ item.last_mac }}"
    order: "{{ lan_assign_order }}"
    state: "{{ lan_state }}"
  with_list: "{{ mac_pool_list }}"
