---
#
# SSH connection may fail for esxcli if previous ssh known_host key has been acquired
#
  - name: Add iSCSI Targets to each host
    command: esxcli iscsi adapter discovery sendtarget add --address='{{ item }}':3260 --adapter=vmhba64
    args:
      warn: false
    with_list: '{{ iscsi_targets }}'
    when: configure_iscsi is defined
