---
# Configure vHBA Templates under organization
# if configure_fc is set
#
- name: Configure vHBA Templates
  ucs_vhba_template:
    hostname: "{{ inventory_hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    org_dn: "org-root/org-{{ organization }}"
    name: "{{ item.name }}"
    fabric: "{{ item.fabric }}"
    template_type: 'initial-template'
    vsan: "{{ item.vsan }}"
    wwpn_pool: "{{ item.wwpn_pool }}"
  with_list: "{{ vhba_list }}"
  when: configure_fc is defined
