# Getting the node-aggr-lif map list
- name: Get the node-aggregate-lif map list
  set_fact:
    node_aggr_lif_map: "{{ node_aggr_lif_map|default([]) + [ {'nfs_lif_ip': item.0.nfs_lifs.address, 'aggr_name': item.1.aggr_name} ] }}"
  with_subelements:
    - "{{ ha_pairs | map(attribute='node_specs') | flatten }}"
    - data_aggregates
  when:
    - item.1.aggr_name is defined and item.1.aggr_name != None
    - item.1.disk_type == "SSD" or item.1.disk_type == "SAS" or item.1.disk_type == "SSD-NVM"
  tags:
    - node_aggr_lif_map

# Getting the NFS datastore and NFS LIF map list
- name: Get the NFS datastore and NFS LIF map list
  set_fact:
    nfs_ds_lif_map: "{{ nfs_ds_lif_map|default([]) + [ {'datastore_name': item.1.name, 'nfs_lif_ip': item.0.nfs_lif_ip} ] }}"
  with_nested:
    - "{{ node_aggr_lif_map }}"
    - "{{ svm_specs.data_volumes }}"
  when: item.0.aggr_name == item.1.residing_aggr
  tags:
    - nfs_ds_lif_map

# Getting the swap datastore and NFS LIF map list
- name: Get the swap datastore and NFS LIF map list
  set_fact:
    swap_ds_lif_map: "{{ swap_ds_lif_map|default([]) + [ {'datastore_name': item.1.name, 'nfs_lif_ip': item.0.nfs_lif_ip} ] }}"
  with_nested:
    - "{{ node_aggr_lif_map }}"
    - "{{ svm_specs.swap_volumes }}"
  when: item.0.aggr_name == item.1.residing_aggr
  tags:
    - swap_ds_lif_map  
