---
# This task configures datacenter on vCenter

  - name: vCenter Datacenter creation
    vmware_datacenter:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      datacenter_name: '{{ vcenter_dc }}'
      state: present
#    delegate_to: localhost
