---
# Configure Power Control Policy to remove power caps

  - name: Configure Power Control Policy
    ucs_managed_objects:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      objects:
      - {
          "module": "ucsmsdk.mometa.power.PowerPolicy",
          "class": "PowerPolicy",
          "properties": {
              "parent_mo_or_dn": "org-root/org-{{ organization }}",
              "name": "{{ power_policy_name }}",
              "prio": "no-cap"
          },
        }
