---
  # This Task enables MDS Features required for setting up FC configuration

  - name: Enable MDS features
    nxos_feature:
      feature: "{{ item }}"
      state: enabled
    with_items: "{{ enabled_mds_features }}"
